image: local-registry.inner.buaaoo.top/image-dev/java:8u201

stages:
  - build
  - test
  
before_script:
  - java -version
  - javac -version
  - mvn -version
  
mvn_build:
  stage: build
  script:
    - echo "Build"
    - mvn compile
  only:
    - se_hw_2
    
mvn_test:
  stage: test
  script:
    - echo "Test"
    - mvn cobertura:cobertura
    - mvn cobertura:dump-datafile
  coverage: '/coverage line-rate="\d+"/'
  only:
    - se_hw_2
